apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
data:
  mosquitto.conf: |
    listener 1883
    allow_anonymous true
    persistence true
    persistence_location /mosquitto/data/
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: z2m-init-config
data:
  configuration.yaml: |
    homeassistant: true
    # Let new devices join our zigbee network
    permit_join: true
    mqtt:
      base_topic: zigbee2mqtt
      server: mqtt://localhost:1883
    # Zigbee Adapter path
    serial:
      port: /dev/ttyACM0
    # Enable the Zigbee2MQTT frontend
    frontend:
      port: 8080
    # Let Zigbee2MQTT generate a new network key on first start
    advanced:
      network_key: GENERATE
--- 
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: homeassistant-z2m
  name: smarthome
spec:
  containers:
  - image: homeassistant/home-assistant:2023.8
    name: homeassistant
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /config
      name: homeassistant-data
  - name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    #command: ["sh", "-c"]
    #args:
    #  - "cp /tmp/configuration.yaml /app/data; DATA=/app/data /sbin/tini -- node index.js"
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /app/data
      name: zigbee2mqtt-data
#    - mountPath: /app
#      name: z2m-init-config
    - mountPath: /run/udev
      name: run-udev
      readOnly: true
    - mountPath: /dev/ttyACM0
      name: dev-ttyacm0 
      
  - image: docker.io/library/eclipse-mosquitto:latest
    name: mosquitto
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /mosquitto/config
      name: mosquitto-config
    - mountPath: /mosquitto/data
      name: mosquitto-data

  volumes:
  - hostPath:
      path: /opt/mosquitto/data
      type: Directory
    name: mosquitto-data
  - name: mosquitto-config
    configMap:
      name: mosquitto-config
  - hostPath:
      path: /opt/zigbee2mqtt/data
      type: Directory
    name: zigbee2mqtt-data
  - name: z2m-init-config
    configMap:
      items:
      - key: configuration.yaml
        path: configuration.yaml
      name: z2m-init-config
  - hostPath:
      path: /run/udev
      type: Directory
    name: run-udev
  - hostPath:
      path: /dev/ttyACM0
      type: CharDevice
    name: dev-ttyacm0
  - hostPath:
      path: /opt/homeassistant
      type: Directory
    name: homeassistant-data
